spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: ${NOTIFICATIONSDB_URL:mongodb://root:root@localhost:27017/notifications}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ORIGIN:finconnect.contact@gmail.com}
    password: ${MAIL_PASSWORD:ouga ldpa sydn jvuh}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  instance:
    prefer-ip-address: true

server:
  port: 0