spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: ${NOTIFICATIONSDB_URL:mongodb://root:root@localhost:27017/notifications}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  instance:
    prefer-ip-address: true

server:
  port: 0