services:
  kafka:
    image: apache/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: 4L62no9PT9unCH9ak3-pAg
  kafka-ui:
    image: kafbat/kafka-ui:main
    ports:
      - 8000:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
  notifications_db:
    image: mongodb/mongodb-community-server
    ports:
      - 27017:27017
    volumes:
      - notifications_volume:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.adminCommand(\"ping\")' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    
  users_db:
    image: postgres:latest
    volumes: 
      - users_volume:/var/lib/postgresql
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=${USERSDB_USERNAME}
      - POSTGRES_PASSWORD=${USERSDB_PASSWORD}
      - POSTGRES_DB=${USERSDB_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USERSDB_USERNAME} -d ${USERSDB_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  accounts_db:
    image: postgres:latest
    ports:
      - 5433:5432
    volumes: 
      - accounts_volume:/var/lib/postgresql
    environment:
      - POSTGRES_USER=${ACCOUNTSDB_USERNAME}
      - POSTGRES_PASSWORD=${ACCOUNTSDB_PASSWORD}
      - POSTGRES_DB=${ACCOUNTSDB_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ACCOUNTSDB_USERNAME} -d ${ACCOUNTSDB_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  transactions_db:
    image: postgres:latest
    ports:
      - 5434:5432
    volumes: 
      - transactions_volume:/var/lib/postgresql
    environment:
      - POSTGRES_USER=${TRANSACTIONSDB_USERNAME}
      - POSTGRES_PASSWORD=${TRANSACTIONSDB_PASSWORD}
      - POSTGRES_DB=${TRANSACTIONSDB_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TRANSACTIONSDB_USERNAME} -d ${TRANSACTIONSDB_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  eureka-server:
    build: ./eureka
    ports: 
      - 8761:8761
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8761/"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 20s

  gateway:
    build: ./gateway
    ports: 
    - 8080:8080
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:-http://eureka-server:8761/eureka/}
      JWT_SECRET: ${JWT_SECRET:-f64fefbfe95bfad56f2e81c8218fee610a72906cc1cbe4abc14b6d9684318826}
    depends_on:
      eureka-server:
        condition: service_healthy

  auth-service:
    build: ./auth-service
    environment:
      DB_URL: ${USERSDB_URL:-jdbc:postgresql://users_db:5432/users_db}
      DB_USERNAME: ${USERSDB_USERNAME:-root}
      DB_PASSWORD: ${USERSDB_PASSWORD:-root}
      JWT_SECRET: ${JWT_SECRET:-f64fefbfe95bfad56f2e81c8218fee610a72906cc1cbe4abc14b6d9684318826}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-3600000}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:-http://eureka-server:8761/eureka/}
    depends_on: 
      users_db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  account-service:
    build: ./account-service
    environment:
      DB_URL: ${ACCOUNTSDB_URL:-jdbc:postgresql://accounts_db:5432/accounts_db}
      DB_USERNAME: ${ACCOUNTSDB_USERNAME:-root}
      DB_PASSWORD: ${ACCOUNTSDB_PASSWORD:-root}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:-http://eureka-server:8761/eureka/}
    depends_on: 
      accounts_db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  transaction-service:
    build: ./transaction-service
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      DB_URL: ${TRANSACTIONSDB_URL:-jdbc:postgresql://transactions_db:5432/transactions_db}
      DB_USERNAME: ${TRANSACTIONSDB_USERNAME:-root}
      DB_PASSWORD: ${TRANSACTIONSDB_PASSWORD:-root}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:-http://eureka-server:8761/eureka/}
    depends_on: 
      transactions_db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_started

  notification-service:
    build: ./notification-service
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      NOTIFICATIONSDB_URL: ${NOTIFICATIONSDB_URL}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:-http://eureka-server:8761/eureka/}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_ORIGIN: ${MAIL_ORIGIN}
    depends_on: 
      notifications_db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_started
      
volumes:
  users_volume:
  accounts_volume:
  transactions_volume:
  notifications_volume: