services:
  users_db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes: 
      - users_volume:/var/lib/postgresql
    environment:
      - POSTGRES_USER=${USERSDB_USERNAME}
      - POSTGRES_PASSWORD=${USERSDB_PASSWORD}
      - POSTGRES_DB=${USERSDB_DB}

  accounts_db:
    image: postgres:latest
    ports:
      - 5431:5432
    volumes: 
      - accounts_volume:/var/lib/postgresql
    environment:
      - POSTGRES_USER=${ACCOUNTSDB_USERNAME}
      - POSTGRES_PASSWORD=${ACCOUNTSDB_PASSWORD}
      - POSTGRES_DB=${ACCOUNTSDB_DB}

volumes:
  users_volume:
  accounts_volume: