spring:
  application:
    name: transaction-service
  datasource:
    url: ${TRANSACTIONSDB_URL:jdbc:postgresql://transactions_db:5432/transactions_db}
    username: ${TRANSACTIONSDB_USERNAME:root}
    password: ${TRANSACTIONSDB_PASSWORD:root}
  flyway:
    enabled: true
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  
springdoc:
  api-docs:
    path: /api/transactions/v3/api-docs
  swagger-ui:
    path: /api/transactions/swagger-ui.html

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  instance:
    prefer-ip-address: true
  
server:
  port: 0