spring:
  application:
    name: account-service
  datasource:
    url: ${ACCOUNTSDB_URL:jdbc:postgresql://accounts_db:5432/accounts_db}
    username: ${ACCOUNTSDB_USERNAME:root}
    password: ${ACCOUNTSDB_PASSWORD:root}
  flyway:
    enabled: true
    baseline-on-migrate: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  instance:
    prefer-ip-address: true
  
server:
  port: 0

logging:
  level:
   root: DEBUG