spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost:5431/accounts_db
    username: root
    password: root
  flyway:
    enabled: true
    baseline-on-migrate: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  
server:
  port: 8090